name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-action@v2
      
    - name: Build and push Docker image
      run: |
        docker build -t my-ml-app .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag my-ml-app ${{ secrets.AWS_REGISTRY_URL }}/my-ml-app
        docker push ${{ secrets.AWS_REGISTRY_URL }}/my-ml-app
    
    - name: SSH into EC2 and pull the latest image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.AWS_REGISTRY_URL }}/my-ml-app
          docker run -d -p 80:80 ${{ secrets.AWS_REGISTRY_URL }}/my-ml-app
