name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Replace with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests with coverage
      run: coverage run -m pytest

    - name: Upload coverage data to Codecov
      run: codecov
